### ISSUE TITLE
Please Add Content Warning for Sensitive Media Similar to Original Posts

### ISSUE THREAD

**Issue by schwarzewald** [stefanbohacek/fediverse-explorer#2]
I’ve noticed that posts tagged with a content warning (CW) on platforms like Mastodon still display sensitive media directly on Fediverse Explorer without the content warning. This behavior can result in users unexpectedly encountering sensitive or explicit content.

Would it be possible to implement a feature that respects content warnings from the original posts? Ideally, the images or sensitive media should be hidden behind a content warning on Fediverse Explorer, just as they are on the original platforms.

This change would improve user experience and help maintain a safer browsing environment, similar to what users expect on platforms like Mastodon.

**Comment by stefanbohacek** [comment]
Hi @schwarzewald, thank you for opening this issue!

It looks like there is an [additional format of CWs](https://github.com/stefanbohacek/fediverse-explorer/commit/30c15c9ecd5c13e98d0f7c2bef1eb9798716d3a6) that I missed, the app already handled at least one form of them. Things should be better now, but please let me know if there's anything I missed.

(Feel free to contact me privately at https://stefanbohacek.com/contact/ if there's a specific hashtag that's not working right.)
